name: Publish LLVM Firtool

on:
  # workflow_dispatch and workflow_call arguments should be kept identical
  # https://github.com/orgs/community/discussions/39357
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of firtool and llvm-firtool to publish'
        required: true
        type: string
      snapshot:
        description: 'Should the version of llvm-resolver be a SNAPSHOT'
        default: true
        required: true
        type: boolean
  workflow_call:
    inputs:
      version:
        description: 'The version of firtool and llvm-firtool to publish'
        required: true
        type: string
      snapshot:
        description: 'Should the version of llvm-resolver be a SNAPSHOT'
        default: true
        required: true
        type: boolean

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yml
    with:
      version: ${{ inputs.version }}
      snapshot: ${{ inputs.snapshot }}

  publish:
    name: Publish LLVM Firtool
    runs-on: ubuntu-24.04
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Scala and Coursier
        uses: coursier/setup-action@fd1707a76b027efdfb66ca79318b4d29b72e5a02 # v3.0.0
        with:
          jvm: temurin:17
      - name: Check if already published
        if: ${{ ! inputs.snapshot }}
        # TODO skip if snapshot
        run: |
          if cs fetch org.chipsalliance:llvm-firtool:${{ inputs.version }} ; then
            echo "llvm-firtool version ${{ inputs.version }} has already been published!" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            exit 0
          fi
      - name: Set versions
        shell: bash
        run: |
          if [[ "${{ inputs.snapshot }}" = 'true' ]]; then
            IS_PRERELEASE=1
          else
            IS_PRERELEASE=0
          fi
          echo "LLVM_FIRTOOL_PRERELEASE=$IS_PRERELEASE" >> "$GITHUB_ENV"
          echo "LLVM_FIRTOOL_VERSION=${{ inputs.version }}" >> "$GITHUB_ENV"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.PGP_SECRET }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}
      - name: Publish
        shell: bash
        run: |
          ./mill -i llvm-firtool.publishSigned
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

